# Generated by Django 4.1.3 on 2022-12-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0002_rename_notes_product_note1_product_note2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
