# Generated by Django 4.1.3 on 2022-12-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0005_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagline',
            name='title',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
