# Generated by Django 4.1.3 on 2022-12-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0006_tagline_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagline',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
